version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "/home/ubuntu/jenkins-data/jenkins_home:/var/jenkins_home"
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: centos7
    networks:
      - net
  
  db:
   container_name: mysql_db
   image: mysql:5.7
   environment:
     MYSQL_ROOT_PASSWORD: "1234"
   volumes:
    - "/home/ubuntu/jenkins-data/mysql-data:/var/lib/mysql"
   networks:
      - net

networks:
  net:

